% GraphONHPerformance
% Copyright University of Lincoln, 2008. Prof. Andrew Hunter,
% ahunter@lincoln.ac.uk.
% This file may not be reproduced or used without the permission of the
% owner.

% Analysis routine
% Generates the "ROC-like" graphs used in the paper to compare results
% of different algorithms.
% Uses information generated by the GlobalClinicianDisparity or LocalClinicianDisparity
% analysis routines.
% Produce a graph of ONH performance. The graph has one line per
% model (indicated by postfix). Each line plots a kind of cumulative
% histogram like entity: the x-axis is the log of the normalized disparity of
% the model from the clinicians; the y-axis is the count of the number of 
% optic nerve heads having less than or equal to that value.
% Basically, a good model should be left and above of a bad one.

function GraphONHPerformance( Postfixes )

% generate the summary stats
s = SummarizeAlgorithm( Postfixes );

% load the "used ONH" array (indicates the 90 which are actually used)
load( 'ONHUsed.mat' );
noONH = size( ONHUsed, 2 );

% copy the used ones into a new array, s2, sorting each column and calculating logs
for i=1:size(s,2)
%    s2( :, i ) = sort(log(s( ONHUsed, i )));
    s2( :, i ) = sort(s( ONHUsed, i ));
end

% plot the s2 elements on X axis versus point number of Y axis
Y = repmat( [1:noONH]', 1, size(s,2) );
plot( s2, Y );

% add the legend to the graph, so we know which is which
legend( Postfixes );
