% MakeONHGlobal
% Copyright University of Lincoln, 2008. Prof. Andrew Hunter,
% ahunter@lincoln.ac.uk.
% This file may not be reproduced or used without the permission of the
% owner.

% Running algorithm en. masse.
% This routine runs the global model fitting procedure on a group of files with specified control parameters,
% and stores the resulting model to files for later analysis.
% Parameters - postfix used for results file. I follow the convention that the
% postfix is a-N-p-atgor where N is the startingRadius, p the pre-process size, a the aspect iterations etc.
% For example, MakeONHGlobal( '1.15-40-7-101000', 40, 7, 1, 0, 1, 0, 0, 0, 1:99 ). Note that startingRadius is always
% two digits, preProcessSize and aspectIterations 1 digit (usually 7 or 0, and 1 or 0 respectively), polo1 and polo2
% are single digit indices and temporal and gridSearch are flags  (0 or 1).

function P = MakeONHGlobal( Postfix, startingAspectRatio, startingRadius, erodeSize, aspectIterations, houghThreshold, temporal, gridSearch, twoD, polo1, polo2, Range )

% Find all bitmap files in the current directory
Files = dir('*.bmp');

% default is to process all files (if no parameter given)
if nargin == 10
    Range=[1:size(Files,1)];
end

% for each image selected
for r=Range
    
    % Display image number and file
    disp( sprintf( '%d: %s', r, Files(r).name ) );
    
    % load the image
    Image = imread( Files(r).name );
    
    % Find initial point by template matching
    ONHCentre = optic_locator( Image );
    
    Image = double(Image(:,:,2))/256;

    % DEBUG section - construct name of dump file. Intermediate results are dumped in here
    % by ONHFitGlobalModel
    global ONHDumpFile;
    [pathstr,name,ext,versn] = fileparts(Files(r).name);
    ONHDumpFile = fullfile( pathstr, 'ONHResults', [name '_' Postfix '_GDump.mat' versn] );
    
    % fit the global model
    [ ONHCentre ONHRadius ONHAspectRatio ]  = ONHFitGlobalModel( Image, ONHCentre(1:2), startingAspectRatio, startingRadius, erodeSize, aspectIterations, houghThreshold, temporal, gridSearch, twoD, polo1, polo2 );
    
    % save the global model file - save the centre, radius and aspect ratio
    [pathstr,name,ext,versn] = fileparts(Files(r).name);
    GlobalFileName = fullfile( pathstr, 'ONHResults', [name '_' Postfix '_G.mat' versn] );
    save( GlobalFileName, 'ONHCentre', 'ONHRadius', 'ONHAspectRatio' );
    
%     % $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
%     % Debug section - display images with model overlaid
%     
%     global ONHGradientImage;
%     
%     % original image
%     figure, imshow(Image);
%     
%     % Display the global model 
%     ONHPlotGlobalModel( ONHCentre, ONHRadius, [ 1 1 0.5 ]  );
%     
%     % display again on the gradient image generated by the routines
%     figure, imshow(ONHGradientImage);
%     
%     % Display the global model
%     ONHPlotGlobalModel( ONHCentre, ONHRadius, [ 1 1 0.5 ]  );
%     
%     % end of debug section
%     % $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
    
end
