% MakeONHLocal
% Copyright University of Lincoln, 2008. Prof. Andrew Hunter,
% ahunter@lincoln.ac.uk.
% This file may not be reproduced or used without the permission of the
% owner.

% Running algorithm en. masse.
% This routine runs the local model fitting procedure on a group of files with specified control parameters,
% and stores the resulting model to files for later analysis. The local model is initialized using the 
% global model results from the file specified by the GlobalPostfix.

function P = MakeONHLocal( GlobalPostfix, LocalPostfix, preProcessSize, alpha, gamma, neighbourhood, inner, outer, Range )

% control parameters. Below were the standard hard-coded values
% alpha = 0.5; % weighting of local versus global forces in internal force
% gamma = 3; % weighting of external versus internal forces
% neighborhood=2; % size of neighborhood in local force
% inner=6; % search range about current model
% outer=6; % ditto

% Find all bitmap files in the current directory
Files = dir('*.bmp');

% default is to process all files (if no parameter given)
if nargin < 9
    Range=[1:size(Files,1)];
end

% for each image selected
for r=Range
    
    % Display image number and file
    disp( sprintf( '%d: %s', r, Files(r).name ) );
    
    % load the image
    Image = imread( Files(r).name );
    Image = double(Image(:,:,2))/256;
    
    % Apply morphological erosion of vessel pre-processing
    if preProcessSize > 0
        Image2 = imclose( Image, strel('disk',preProcessSize) );
    else
        Image2 = Image;
    end    
    
    % now load the ONH global file. This loads the global model centre and radius and aspect ratio
    % ONHCentre and ONHRadius and ONHAspectRatio
    [pathstr,name,ext,versn] = fileparts(Files(r).name);
    GlobalFileName = fullfile( pathstr, 'ONHResults', [name '_' GlobalPostfix '_G.mat' versn] );
    if exist( GlobalFileName, 'file')
        load( GlobalFileName );
    else
        disp( sprintf( 'Global model file %s not found', GlobalFileName ) );
        continue;
    end
    
    GlobalCentre = ONHCentre;
    
    % fit the local model
    [ ONHCentre ONHSpokes ]  = ONHFitLocalModel( Image2, ONHCentre, ONHRadius, 1.0, inner, outer, neighbourhood, alpha, gamma, ONHAspectRatio );

    % save local model to file
    LocalFileName = fullfile( pathstr, 'ONHResults', [name '_' GlobalPostfix '_' LocalPostfix '_L.mat', versn] );
    save( LocalFileName, 'ONHCentre', 'ONHSpokes' );
    
%     % $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
%     % Debug section - display images with model overlaid
%     
%     global ONHGradientImage;
%     
%     % original image
%     figure, imshow(Image);
%     
%     % Display the global model 
%     ONHPlotGlobalModel( GlobalCentre, ONHRadius, ONHAspectRatio, [ 1 1 0.5 ]  );
%     
%     % Display the local model in red
%     ONHPlotLocalModel( ONHCentre, ONHSpokes, [1 0.2 0.2] );
%     
%     % display again on the gradient image generated by the routines
%     figure, imshow(ONHGradientImage);
%     
%     % Display the global model
%     ONHPlotGlobalModel( GlobalCentre, ONHRadius, ONHAspectRatio, [ 1 1 0.5 ]  );
%     
%     % Display the local model in red
%     ONHPlotLocalModel( ONHCentre, ONHSpokes, [1 0.2 0.2] );
%     
%     % end of debug section
%     % $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
    
end
