% SummarizeAlgorithm
% Copyright University of Lincoln, 2008. Prof. Andrew Hunter,
% ahunter@lincoln.ac.uk.
% This file may not be reproduced or used without the permission of the
% owner.

% Analysis routine.
% Given a set of postfixes, determines the 
% mean normalized disparities per image and returns.
% Disparities must have been previously generated by GlobalClinicianDisparity or LocalClinicianDisparity

function s = SummarizeAlgorithm( Postfixes )

% split path name
Files = dir('*.bmp');
[pathstr,name,ext,versn] = fileparts(Files(1).name); 

for i=1:size(Postfixes,2)

    % now read the disparities from file
    ONHDisparityFileName = fullfile( pathstr, 'ONHResults', ['Disparity_' Postfixes{i} '.mat' versn] );
    load( ONHDisparityFileName, 'ONHDisparity', 'ONHNormDisparity' );
    d = ONHDisparity;
    nd = ONHNormDisparity;
    
    a = min( nd, 2 );
    b = max( nd, 2 );
    c = mean( nd, 2 );
    
    s(:,i) = c;
end